settings:
  title: 'TCPGuard Network Status'
  url: 'https://status.tcpguard.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 5 # number of days you want to display in histogram
  collectResponseTimes: true # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: TCPGuard # unique identifier
    name: TCPGuard.com
    description: 'TCPGuard Main' # default=empty
    url: 'https://TCPGuard.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: CheatLoop # unique identifier
    name: cheatloop.com
    description: 'CheatLoop' # default=empty
    url: 'https://cheatloop.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false



    
